#!/usr/bin/env bash
# use for installing nginx web server

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
ufw allow 'Nginx HTTP'
service nginx start
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
